create schema ict_342_project;
use ict_342_project;

DROP TABLE IF EXISTS PROJECT_GROUPS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PROJECTS;

CREATE TABLE PROJECTS(
PROJECT_ID VARCHAR(10),
PROJECT_NAME VARCHAR(25) UNIQUE,
PROJECT_SPONSOR VARCHAR(30),
PROJECT_DESCRIPTION VARCHAR(1000),
PROJECT_START_DATE DATE,
PROJECT_DEADLINE DATE,
PROJECT_ROLE_REQUIREMENTS VARCHAR(100),
PRIMARY KEY(PROJECT_ID)
);

CREATE TABLE USERS(
USER_ID	VARCHAR(10),
LAST_NAME VARCHAR(20),
FIRST_NAME VARCHAR(20),
EMAIL VARCHAR(50),
PHONE_NUMBER VARCHAR(10),
PASSWORD VARCHAR(20),
PROJECT_PREFERENCE VARCHAR(25),
SECOND_PROJECT_PREFERENCE VARCHAR(25),
USER_TYPE VARCHAR(30),
PRIMARY KEY(USER_ID),
FOREIGN KEY(PROJECT_PREFERENCE) REFERENCES PROJECTS(PROJECT_NAME)
);

CREATE TABLE PROJECT_GROUPS(
GROUP_ID VARCHAR(10),
PROJECT_ID VARCHAR(10),
USER_ID VARCHAR(10),
GROUP_NAME VARCHAR(50),
STUDENT_ROLES VARCHAR(20),
PRIMARY KEY(GROUP_ID, PROJECT_ID, USER_ID),
FOREIGN KEY(PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);

INSERT INTO PROJECTS(PROJECT_ID, PROJECT_NAME, PROJECT_SPONSOR, PROJECT_DESCRIPTION, PROJECT_START_DATE, PROJECT_DEADLINE, PROJECT_ROLE_REQUIREMENTS)
VALUES('Project_01', 'Co-op Nursery Database', 'Cameron Smith', 'Create a database for Co-op Nursery that keeps track of all orders that customers make through the nursery. The database should also keep an inventory of all plants and their varieties', '2020-03-10', '2020-06-10', 'Project Manager, Business Analyst, Programmer');

SELECT * FROM PROJECTS;

INSERT INTO USERS(USER_ID, LAST_NAME, FIRST_NAME, EMAIL, PHONE_NUMBER, PASSWORD, PROJECT_PREFERENCE, SECOND_PROJECT_PREFERENCE, USER_TYPE)
VALUES('jjs019', 'Sperling', 'Jeffrey', 'jjs019@student.usc.edu.au', '0489265663', 'pass01', 'Co-op Nursery Database', NULL, 'Student'),
		('jws003', 'Smiles', 'John', 'jws003@student.usc.edu.au', '0457696721', 'pass02', 'Co-op Nursery Database', NULL, 'Student'),
		('whg101', 'Giles', 'Will', 'whg101@usc.edu.au', '54402541', 'unipass90', NULL, NULL, 'Course Coordinator'); 

SELECT * FROM USERS; 

INSERT INTO PROJECT_GROUPS(GROUP_ID, PROJECT_ID, USER_ID, GROUP_NAME, STUDENT_ROLES)
VALUES('Group_01', 'Project_01', 'jjs019', 'Group A', 'Business Analyst'),
		('Group_01', 'Project_01', 'jws003', 'Group A', 'Project Manager');

SELECT * FROM PROJECT_GROUPS;
